default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "stratum") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

development:
  <<: *default
  database: stratum_dashboard_development

production:
  <<: *default
  database: stratum_dashboard_production
